twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['base_form_theme.html.twig']
    paths:
        '%kernel.project_dir%/emails/css': emails_css
        '%kernel.project_dir%/emails/templates': emails_templates

when@test:
    twig:
        strict_variables: true
